### ISSUE TITLE
Build fails due to could not resolve ai.forethought:solve-android-source:0.1.0

### ISSUE THREAD

**Issue by ZihaoGuan** [Forethought-Technologies/solve-android#5]
Hi

Demo project build fails due to Could not resolve ai.forethought:solve-android-source:0.1.0. It reads `Caused by: org.gradle.internal.resource.transport.http.HttpErrorStatusCodeException: Could not GET 'https://jitpack.io/ai/forethought/solve-android-source/0.1.0/solve-android-source-0.1.0.pom'. Received status code 401 from server: Unauthorized`

**Comment by Pesof1** [comment]
Hello,
This seems like caching issue on our repositories, it will be fixed with our next release.
In the meantime, please use this dependency instead:

`implementation("com.github.Forethought-Technologies:solve-android-source:0.1.0")`

**Comment by Pesof1** [comment]
Hi,
Thanks for reporting this! apparently it's a caching issue on our repository, this will be fixed in the next release.
In the meantime, you can use the indirect dependencies like this.

object Forethought {
        const val core = "com.github.Forethought-Technologies:solve-android-source:core:0.1.0"
        const val solve = "com.github.Forethought-Technologies:solve-android-source:0.1.0"
    }

**Comment by ZihaoGuan** [comment]
Hi @Pesof1 ,

Thank you for your reply.

I tried to add dependencies like 

`implementation("com.github.Forethought-Technologies:solve-android-source:core:0.1.0")
    implementation("com.github.Forethought-Technologies:solve-android-source:0.1.0")`

But we get "Failed to resolve: solve-android-source-0.1.0-0.1.0"

**Comment by Pesof1** [comment]
Hello @ZihaoGuan ,
It seems that the dependency version is added twice (0.1.0-0.1.0).
Can you please share the Forethought object block in Dependencies.kt?
Like the one I shared in my previous reply.

**Comment by ZihaoGuan** [comment]
Hi, it seems like I haven't set up Dependencies.kt properly. Now 'Failed to resolve: solve-android-source-0.1.0-0.1.0' error doesn't show up again, but getting a `A failure occurred while executing com.android.build.gradle.internal.tasks.MergeJavaResWorkAction` issue which I am now looking into it now.

**Comment by ZihaoGuan** [comment]
Btw, is there a workaround to resolve the Solve SDK dependency issue in Groovy?

**Comment by Pesof1** [comment]
Hello,
Sure thing, for groovy just use: 

```
implementation "com.github.Forethought-Technologies:solve-android-source:core:0.1.0"

implementation "com.github.Forethought-Technologies:solve-android-source:0.1.0"
```

**Comment by ZihaoGuan** [comment]
> Hello, Sure thing, for groovy just use:
> 
> ```
> implementation "com.github.Forethought-Technologies:solve-android-source:core:0.1.0"
> 
> implementation "com.github.Forethought-Technologies:solve-android-source:0.1.0"
> ```

Yeah. I tried to build adding the same block as you advised, but got a similar error like "Failed to resolve: solve-android-source-0.1.0-0.1.0. 

> dependencies {
>     def forethought = [ 'core' : "com.github.Forethought-Technologies:solve-android-source:core:0.1.0" ,
>                         'solve' : 'com.github.Forethought-Technologies:solve-android-source:0.1.0' 
>    .....
>     implementation forethought.solve
> }
Then I changed a bit and it works now.
