### ISSUE TITLE
Build failure due to not able to get pom file

### ISSUE THREAD

**Issue by ZihaoGuan** [Forethought-Technologies/solve-android#8]
Hi there,

We are trying to build our app which includes Forethought as one of the dependencies. But it went wrong with the following error.

  > Could not resolve ai.forethought:solve-android-source:0.1.0.
     Required by:
         project :app
      > Could not resolve ai.forethought:solve-android-source:0.1.0.
         > Could not get resource 'https://jitpack.io/ai/forethought/solve-android-source/0.1.0/solve-android-source-0.1.0.pom'.
            > Could not GET 'https://jitpack.io/ai/forethought/solve-android-source/0.1.0/solve-android-source-0.1.0.pom'. Received status code 403 from server: Forbidden

We also tried to get https://jitpack.io/ai/forethought/solve-android-source/0.1.0/solve-android-source-0.1.0.pom.

> Subscription is not active right now
Requested subscription: github.com/forethought-technologies. 
Your subscriptions are listed in https://jitpack.io/w/user
Please contact Support or repository admins if you need assistance.

Could you have a look and help with that? Thanks

**Comment by djorka** [comment]
@ZihaoGuan This should be fixed now. Apologies for the late response.
